apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
spec:
  replicas:  {{ .Values.movieDeployment.replicas }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image:  {{ .Values.movieDeployment.image }}

        ports:
        - containerPort: {{ .Values.movieDeploymentPort.port }}
        env:
        - name: DATABASE_URI
          value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast_service:8000/api/v1/casts/"
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
